In [2]:
import numpy as np
matrix = np.loadtxt('D:\Msit\DADV\diabetes.csv', skiprows=1, delimiter=',')

In [3]:
matrix

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [4]:
matrix.shape

(768, 9)

In [9]:
matrix[5, 2]

74.0

In [10]:
matrix[112, 7]

23.0

In [11]:
matrix[227, 8]

1.0

In [12]:
sum(matrix[:, 8] == 1)

268

In [13]:
sum(matrix[:, 4] == 0)

374

In [14]:
sum( (matrix[:, 1] == 0) | (matrix[:, 2] == 0) | (matrix[:, 3] == 0) | (matrix[:, 4] == 0) | (matrix[:, 5] == 0) | (matrix[:, 6] == 0) | (matrix[:, 7] == 0) )

376

In [15]:
bad = (matrix[:, 1] == 0) | (matrix[:, 2] == 0) | (matrix[:, 3] == 0) | (matrix[:, 4] == 0) | (matrix[:, 5] == 0) | (matrix[:, 6] == 0) | (matrix[:, 7] == 0)
new = matrix[np.logical_not(bad), :]
new.shape

(392, 9)

In [17]:
sum(new[:, 8] == 1)

130

In [18]:
np.mean(new, axis=0)

array([  3.30102041, 122.62755102,  70.66326531,  29.14540816,
       156.05612245,  33.08622449,   0.52304592,  30.86479592,
         0.33163265])

In [20]:
diabetic = new[ (new[:, 8] == 1) , :]
np.mean(diabetic, axis=0)

array([  4.46923077, 145.19230769,  74.07692308,  32.96153846,
       206.84615385,  35.77769231,   0.62558462,  35.93846154,
         1.        ])

In [22]:
non_diabetic = new[ (new[:, 8] == 0) , :]
np.mean(non_diabetic, axis=0)

array([  2.72137405, 111.43129771,  68.96946565,  27.2519084 ,
       130.85496183,  31.75076336,   0.47216794,  28.34732824,
         0.        ])

In [1]:
import pandas as pd
dataset = pd.read_csv('D:\Msit\DADV\diabetes.csv')
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [2]:
dataset.iloc[2]


Pregnancies                   8.000
Glucose                     183.000
BloodPressure                64.000
SkinThickness                 0.000
Insulin                       0.000
BMI                          23.300
DiabetesPedigreeFunction      0.672
Age                          32.000
Outcome                       1.000
Name: 2, dtype: float64

In [3]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [4]:
sum(dataset["Glucose"]==0)

5

In [5]:
new=(dataset['Glucose']==0)
dataset.loc[new,'Glucose']=None
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     763 non-null float64
BloodPressure               768 non-null int64
SkinThickness               768 non-null int64
Insulin                     768 non-null int64
BMI                         768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Outcome                     768 non-null int64
dtypes: float64(3), int64(6)
memory usage: 54.1 KB


In [6]:
for col in ['BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction']:
    temp = (dataset[col]==0)
    dataset.loc[temp,col]=None



In [7]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     763 non-null float64
BloodPressure               733 non-null float64
SkinThickness               541 non-null float64
Insulin                     394 non-null float64
BMI                         757 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Outcome                     768 non-null int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB


In [8]:
dataset.describe()


Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  763.000000     733.000000     541.000000  394.000000   
mean      3.845052  121.686763      72.405184      29.153420  155.548223   
std       3.369578   30.535641      12.382158      10.476982  118.775855   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.000000      64.000000      22.000000   76.250000   
50%       3.000000  117.000000      72.000000      29.000000  125.000000   
75%       6.000000  141.000000      80.000000      36.000000  190.000000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  757.000000                768.000000  768.000000  768.000000  
mean    32.457464                  0.471876   33.240885    0.348958  
std      6.924988                  0.331329   11.760232    0.476951  
min     18.200000                  0.078000   21.000000    0.000000  
25%     27.500000                  0.243750   24.000000    0.000000  
50%     32.300000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
dataset.corrwith(dataset['Outcome'])

Pregnancies                 0.221898
Glucose                     0.494650
BloodPressure               0.170589
SkinThickness               0.259491
Insulin                     0.303454
BMI                         0.313680
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
dtype: float64

In [13]:
print(dataset['Pregnancies'].corr(dataset['Age']))
print(dataset['Pregnancies'].corr(dataset['SkinThickness']))
print(dataset['Pregnancies'].corr(dataset['BMI']))

0.544341228402339
0.10023907244218411
0.02171891931714609


In [14]:
print(dataset['SkinThickness'].corr(dataset['Age']))
print(dataset['SkinThickness'].corr(dataset['BloodPressure']))
print(dataset['SkinThickness'].corr(dataset['BMI']))

0.16681577419885846
0.22683906740782175
0.6482139430923206


In [17]:
normalized_dataset= (dataset-dataset.mean())/dataset.std()

In [18]:
normalized_dataset.mean()

Pregnancies                 2.977942e-17
Glucose                     1.002547e-16
BloodPressure              -5.239480e-16
SkinThickness              -3.006426e-17
Insulin                    -6.903671e-18
BMI                         3.449978e-15
DiabetesPedigreeFunction    1.913039e-15
Age                         2.198762e-16
Outcome                     3.189000e-16
dtype: float64

In [19]:
normalized_dataset.std()


Pregnancies                 1.0
Glucose                     1.0
BloodPressure               1.0
SkinThickness               1.0
Insulin                     1.0
BMI                         1.0
DiabetesPedigreeFunction    1.0
Age                         1.0
Outcome                     1.0
dtype: float64

In [20]:
normalized_dataset.iloc[2]

Pregnancies                 1.233077
Glucose                     2.007924
BloodPressure              -0.678814
SkinThickness                    NaN
Insulin                          NaN
BMI                        -1.322380
DiabetesPedigreeFunction    0.604004
Age                        -0.105515
Outcome                     1.365006
Name: 2, dtype: float64

In [23]:
cols=list(normalized_dataset.columns)[:-1]
for column in cols:
    temp=normalized_dataset[column].isnull()
    normalized_dataset.insert(0,"%s_isNull" % column,temp)
normalized_dataset[normalized_dataset.isnull()]=0.0
normalized_dataset = normalized_dataset.applymap(float)

In [24]:
normalized_dataset.head()

Age_isNull  DiabetesPedigreeFunction_isNull  BMI_isNull  Insulin_isNull  \
0         0.0                              0.0         0.0             1.0   
1         0.0                              0.0         0.0             1.0   
2         0.0                              0.0         0.0             1.0   
3         0.0                              0.0         0.0             0.0   
4         0.0                              0.0         0.0             0.0   

   SkinThickness_isNull  BloodPressure_isNull  Glucose_isNull  \
0                   0.0                   0.0             0.0   
1                   0.0                   0.0             0.0   
2                   1.0                   0.0             0.0   
3                   0.0                   0.0             0.0   
4                   0.0                   0.0             0.0   

   Pregnancies_isNull  Pregnancies   Glucose  BloodPressure  SkinThickness  \
0                 0.0     0.639530  0.861722      -0.032723       0.558040   
1                 0.0    -0.844335 -1.201441      -0.517291      -0.014643   
2                 0.0     1.233077  2.007924      -0.678814       0.000000   
3                 0.0    -0.844335 -1.070446      -0.517291      -0.587327   
4                 0.0    -1.141108  0.501487      -2.617087       0.558040   

    Insulin       BMI  DiabetesPedigreeFunction       Age   Outcome  
0  0.000000  0.164987                  0.468187  1.425067  1.365006  
1  0.000000 -0.845845                 -0.364823 -0.190548 -0.731643  
2  0.000000 -1.322380                  0.604004 -0.105515  1.365006  
3 -0.518188 -0.629238                 -0.920163 -1.040871 -0.731643  
4  0.104834  1.536831                  5.481337 -0.020483  1.365006